#!/usr/bin/env python3
"""
Extract per-tree XY centers from TreeAIBox volume JSON files.

Input:
    Folder containing files named like tree_<id>.json

Output:
    - CSV with tree centers (default)
    - Optional GeoJSON Point file for GIS tools (ArcGIS, QGIS, etc.)

How the center is computed:
    - Reads section-level `circle_data.avg_center` values.
    - Ignores `global_extrapolated` sections by default.
    - Computes a weighted mean center per tree using `num_points` as weight.
      (Falls back to simple mean when weights are missing/zero.)
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import os
from dataclasses import dataclass
from typing import Any, Dict, Iterable, List, Optional, Tuple


@dataclass
class TreeCenter:
    tree_id: str
    center_x: float
    center_y: float
    section_count_used: int
    source_file: str
    dbh_cm: Optional[float] = None  # DBH at 1.3m in centimeters


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract tree centers from TreeAIBox volume JSON files."
    )
    parser.add_argument(
        "input_folder",
        help="Folder containing tree_*.json files generated by TreeAIBox.",
    )
    parser.add_argument(
        "--output-csv",
        default="tree_centers.csv",
        help="Output CSV file path (default: tree_centers.csv in current directory).",
    )
    parser.add_argument(
        "--output-geojson",
        default=None,
        help="Optional output GeoJSON file path.",
    )
    parser.add_argument(
        "--include-extrapolated",
        action="store_true",
        help="Include sections with section_id='global_extrapolated' in center averaging.",
    )
    return parser.parse_args()


def iter_tree_files(input_folder: str) -> Iterable[str]:
    pattern = os.path.join(input_folder, "tree_*.json")
    for path in sorted(glob.glob(pattern)):
        if os.path.isfile(path):
            yield path


def extract_tree_id(file_path: str, fallback: str) -> str:
    name = os.path.basename(file_path)
    stem = os.path.splitext(name)[0]
    if stem.startswith("tree_"):
        return stem[len("tree_") :]
    return fallback


def section_center_and_weight(
    section: Dict[str, Any], include_extrapolated: bool
) -> Optional[Tuple[float, float, float]]:
    section_id = section.get("section_id")
    if section_id == "global_extrapolated" and not include_extrapolated:
        return None

    circle_data = section.get("circle_data") or {}
    avg_center = circle_data.get("avg_center")
    if not isinstance(avg_center, (list, tuple)) or len(avg_center) < 2:
        return None

    try:
        center_x = float(avg_center[0])
        center_y = float(avg_center[1])
    except (TypeError, ValueError):
        return None

    num_points = section.get("num_points", 1)
    try:
        weight = float(num_points)
    except (TypeError, ValueError):
        weight = 1.0

    if weight < 0:
        weight = 0.0

    return center_x, center_y, weight


def compute_tree_center(
    sections: List[Dict[str, Any]], include_extrapolated: bool
) -> Optional[Tuple[float, float, int]]:
    usable: List[Tuple[float, float, float]] = []
    for section in sections:
        result = section_center_and_weight(section, include_extrapolated)
        if result is not None:
            usable.append(result)

    if not usable:
        return None

    total_weight = sum(weight for _, _, weight in usable)
    count = len(usable)

    if total_weight > 0:
        mean_x = sum(x * w for x, _, w in usable) / total_weight
        mean_y = sum(y * w for _, y, w in usable) / total_weight
    else:
        mean_x = sum(x for x, _, _ in usable) / count
        mean_y = sum(y for _, y, _ in usable) / count

    return mean_x, mean_y, count


def extract_dbh_from_sections(sections: List[Dict[str, Any]]) -> Optional[float]:
    """Extract DBH at 1.3m from first section that has it, return in centimeters."""
    for section in sections:
        circle_data = section.get("circle_data") or {}
        dbh_at_1_3m = circle_data.get("dbh_at_1_3m")
        if dbh_at_1_3m is not None:
            try:
                dbh_meters = float(dbh_at_1_3m)
                if dbh_meters > 0:
                    return dbh_meters * 100.0  # Convert meters to centimeters
            except (TypeError, ValueError):
                continue
    return None


def load_tree_center(file_path: str, include_extrapolated: bool) -> Optional[TreeCenter]:
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return None

    sections = data.get("sections")
    if not isinstance(sections, list):
        return None

    computed = compute_tree_center(sections, include_extrapolated)
    if computed is None:
        return None

    center_x, center_y, section_count = computed
    tree_id = str(data.get("tree_id") or extract_tree_id(file_path, "unknown"))
    dbh_cm = extract_dbh_from_sections(sections)
    
    return TreeCenter(
        tree_id=tree_id,
        center_x=center_x,
        center_y=center_y,
        section_count_used=section_count,
        source_file=os.path.basename(file_path),
        dbh_cm=dbh_cm,
    )


def write_csv(output_csv: str, rows: List[TreeCenter]) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(output_csv)), exist_ok=True)
    with open(output_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["tree_id", "center_x", "center_y", "dbh_cm", "section_count_used", "source_file"])
        for row in rows:
            dbh_str = f"{row.dbh_cm:.2f}" if row.dbh_cm is not None else ""
            writer.writerow(
                [
                    row.tree_id,
                    f"{row.center_x:.6f}",
                    f"{row.center_y:.6f}",
                    dbh_str,
                    row.section_count_used,
                    row.source_file,
                ]
            )


def write_geojson(output_geojson: str, rows: List[TreeCenter]) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(output_geojson)), exist_ok=True)
    features = []
    for row in rows:
        properties = {
            "tree_id": row.tree_id,
            "section_count_used": row.section_count_used,
            "source_file": row.source_file,
        }
        if row.dbh_cm is not None:
            properties["dbh_cm"] = round(row.dbh_cm, 2)
        
        features.append(
            {
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [row.center_x, row.center_y],
                },
                "properties": properties,
            }
        )

    collection = {
        "type": "FeatureCollection",
        "features": features,
    }

    with open(output_geojson, "w", encoding="utf-8") as f:
        json.dump(collection, f, indent=2)


def main() -> int:
    args = parse_args()
    input_folder = args.input_folder

    if not os.path.isdir(input_folder):
        print(f"Error: input folder does not exist: {input_folder}")
        return 1

    tree_files = list(iter_tree_files(input_folder))
    if not tree_files:
        print(f"Error: no tree_*.json files found in: {input_folder}")
        return 1

    rows: List[TreeCenter] = []
    skipped = 0

    for file_path in tree_files:
        center = load_tree_center(file_path, args.include_extrapolated)
        if center is None:
            skipped += 1
            continue
        rows.append(center)

    if not rows:
        print("Error: no valid centers extracted from the input files.")
        return 1

    rows.sort(key=lambda r: (r.tree_id, r.source_file))

    write_csv(args.output_csv, rows)
    print(f"CSV written: {args.output_csv} ({len(rows)} trees)")

    if args.output_geojson:
        write_geojson(args.output_geojson, rows)
        print(f"GeoJSON written: {args.output_geojson} ({len(rows)} points)")

    if skipped:
        print(f"Skipped files with missing/invalid center data: {skipped}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
